# example workflow for Polaris scans using the Synopsys Action
# https://github.com/marketplace/actions/synopsys-action
name: polaris
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  polaris:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
      # - name: npmsetup
      # You may pin to the exact commit or the version.
      # uses: ng-easy/npm-setup@e5cc43439b1b38d58809e979c44bc442e2a89ac5
      # uses: ng-easy/npm-setup@v1.7.2 
      # with:
      # run: npm run build
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: microsoft 
    - name: Polaris Scan 2
      uses: synopsys-sig/synopsys-action@v1.8.0
      with:
        polaris_server_url: ${{ vars.POLARIS_SERVERURL }}
        polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
        polaris_assessment_types: 'SAST,SCA'
        # polaris_application_name: JWtest-${{ github.event.repository.name }}
        polaris_application_name: JWtest
        polaris_project_name: ${{ github.event.repository.name }}
        # polaris_project_name: "HelloJava"
        # polaris_branch_name: main
        polaris.branch.parent.id: main
        polaris_prComment_enabled: ${{ github.event_name == 'pull_request' && 'true' || 'false' }}
        polaris_reports_sarif_create: ${{ github.event_name != 'pull_request' && 'true' || 'false' }}
        polaris_upload_sarif_report: ${{ github.event_name != 'pull_request' && 'true' || 'false' }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
#    - name: Save Logs
#      if: always()
#      uses: actions/upload-artifact@v4
#      with:
#        name: bridge-logs
#        path: ${{ github.workspace }}/.bridge
